name: nabbit
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0

dependencies: 
  args: ^2.3.0
  tint: ^2.0.0
  http: ^0.13.4
